config/routes.rb
RssReader::Application.routes.draw do

  root :to => "channels#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks, :registrations => 'registrations'}
  ActiveAdmin.routes(self)

  resources :users, :only => :show
  
  resources :channels

  namespace :articles do
    resources :comments, :only => [:new, :create]
    post :star, :controller => :articles
    get :starred, :controller => :articles
    get :all, :controller => :articles
  end
  
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  require 'feedzirra'

  attr_accessible :name, :url, :user_id

  belongs_to :user
  has_many :articles, :dependent => :destroy

  validates :name, :url, :user_id, :presence => true

  searchable do
    text :name
  end

  def self.can_add_channel?(user)
    allowed = user.profile_type == 'basic' ? 1 : user.profile_type == 'medium' ? 20 : 100
    user.channel_count < allowed ? true : false
  end

  # Add a new channel
  def self.fetch_from_url(feed_url, user_id)
    feed = Feedzirra::Feed.fetch_and_parse(feed_url)
    unless feed.nil? || feed.class == Fixnum
      channel = Channel.create(:name     => feed.title,
                                :url     => feed_url,
                                :user_id => user_id)
      channel.add_entries(feed.entries)
      channel
    end
  end

  # Cron update channels
  def self.cron_update
    Channel.all_urls.each do |channel|
      feed = Feedzirra::Feed.fetch_and_parse(channel.url)
      updated_feed = Feedzirra::Feed.update(feed)
      channel.add_entries(updated_feed.new_entries) if updated_feed.updated?
    end
  end

  #Add articles to a channel
  def add_entries(entries)
    entries.each do |entry|
      description = entry.content || entry.summary
      Article.create!(
        :title        => entry.title,
        :description  => description,
        :link         => entry.url,
        :pubDate      => entry.published,
        :guid         => entry.id,
        :channel_id   => self.id,
        :starred      => false)
    end
  end

  private

  def self.all_urls
    self.find(:all, :select => [:id, :url])
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :authenticate_user!
  # GET /channels
  # GET /channels.json
  def index
    @user = current_user

    if params[:search].present?
      @search = @user.channels.solr_search do
        fulltext params[:search]
      end
      @channels = @search.results
    else
      @channels = @user.channels
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @user = current_user
    @channel = @user.channels.find(params[:id])

    if params[:search].present?
      @search = @channel.articles.solr_search do
        fulltext params[:search]
        with(:channel_id, params[:id])
      end
      @articles = @search.results
    else
      @articles = @channel.articles.order('"pubDate" DESC')
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @user = current_user
    @channel = @user.channels.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @user = current_user
    @channel = @user.channels.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @user = current_user
    @channel = Channel.fetch_from_url(params[:channel][:url], current_user.id) unless params[:channel][:url].blank?
      
    respond_to do |format|
      if @channel
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { 
          flash[:alert] = 'The provided url is not a RSS/Atom valid source.'
          flash.keep
          redirect_to action: "new"
        }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @user = current_user
    @channel = @user.channels.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @user = current_user
    @channel = @user.channels.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.slim
= form_for @channel do |f|
  - if @channel.errors.any?
    #error_explanation.page-actions
      h3
        = pluralize(@channel.errors.count, "error")
        | prohibited this channel from being saved:
      ul
        - @channel.errors.full_messages.each do |msg|
          li= msg
          
  - if @channel.id
    .field
      = f.label :name
      = f.text_field :name
  - unless @channel.id
    .field
      = f.label :url
      = f.text_field :url
  .actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/channels/edit.html.slim
h2.title = t('navigation.titles.edit', :model => Channel.model_name.human)

div class='page-actions right-align'
  = link_to t('actions.show'), @channel

= render 'form'

app/views/channels/index.html.slim
h2.title
  = t('navigation.titles.list', :model => Channel.model_name.human(:count => 2))

.page-actions
  = link_to new_channel_path, :class => 'btn btn-primary pull-right' do
    i class="icon-plus-sign" 
    = t('actions.new', :model => Channel.model_name.human)

  = form_tag channels_path, :method => :get, :class => 'form-search' do
    = text_field_tag :search, params[:search], :class => 'search-query'
    = submit_tag t('actions.search'), :class => 'btn'

table class="table table-hover table-bordered"
  thead
    tr
      th = Channel.human_attribute_name :name
      th = t('actions.actions')
  - @channels.each do |channel|
      tr
        td= link_to channel.name, channel_path(channel), :class => 'channel-name'
        td= link_to 'Edit', edit_channel_path(channel)
        td= link_to 'Destroy', channel, method: :delete, :data => {confirm: t("actions.delete.confirm")}

app/views/channels/new.html.slim
h2.title = t('navigation.titles.new', :model => Channel.model_name.human)

div class='page-actions right-align'
  = link_to t('actions.back'), channels_path

- if Channel.can_add_channel?(@user)
  = render 'form'
- else
  .not-allowed = t('messages.error.cannot_add_channel')

app/views/channels/show.html.slim
h2.title = @channel.name

.page-actions
  div.pull-right
    = link_to t('actions.edit', :model => Channel.model_name.human), edit_channel_path(@channel), :class => 'btn btn-primary mbottom'
    div
      = link_to t('actions.back'), channels_path, :class => 'pull-right'
  = form_tag channel_path, :method => :get, :class => 'form-search' do
    = text_field_tag :search, params[:search], :class => 'search-query'
    = submit_tag t('actions.search'), :class => 'btn'

.articles-list
  = render :partial => 'articles/articles/article', :collection => @articles, :as => :article