config/routes.rb
RssReader::Application.routes.draw do

  root :to => "channels#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks, :registrations => 'registrations'}
  ActiveAdmin.routes(self)

  resources :users, :only => :show
  
  resources :channels

  namespace :articles do
    resources :comments, :only => [:new, :create]
    post :star, :controller => :articles
    get :starred, :controller => :articles
    get :all, :controller => :articles
  end
  
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :channel_id, :description, :guid, :link, :pubDate, :title, :starred

  validates :title, :link, :description, :guid, :channel_id, :pubDate, :presence => true
  validates :guid, :uniqueness => true

  has_many :comments, :dependent => :destroy

  searchable do
    text :title, :boost => 2
    text :description
    integer :channel_id
  end

  def star_article
    self.toggle(:starred).save
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :body, :user_id

  belongs_to :article
  belongs_to :user
end

app/controllers/articles/articles_controller.rb
class Articles::ArticlesController < ApplicationController
  def all
    @user = current_user
    @articles = @user.articles
  end

  def star
    @user = current_user
    @article = Article.find(params[:article_id])
    
    if @article.star_article
      respond_to do |format|
        format.html{ render :partial => 'star', :locals => {:article => @article}, :layout => false}
      end
    end
  end

  def starred
    @user = current_user
    @articles = current_user.starred_articles
  end  
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  # GET /comments/new
  # GET /comments/new.json
  def new
    @user = current_user
    @article = Article.find(params[:article_id])
    @comments = @article.comments
    @comment = Comment.new(user_id: params[:user_id], article_id: params[:article_id])

    respond_to do |format|
      format.html{ render 'articles/comments/new',:layout => false}
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @user = current_user
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html{ render :partial => 'articles/comments/comment', :locals => {:comment => @comment},:layout => false }
      else
        format.html { render :text => 'There was an error when posting your comment, please try again later' }
      end
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/comments/_comment.html.slim
.media
  = link_to user_path(@user), :class => 'pull-left' do
    = image_tag @user.avatar_url(:ico) if @user.avatar?
  .media-body
    div class="help-block pull-right comment-date"
      = time_ago_in_words comment.created_at
    .body
      = comment.body

app/views/articles/comments/_form.html.slim
= form_for [:articles, @comment], :remote => true do |f|
  - if @comment.errors.any?
    #error_explanation
      h6
        = pluralize(@comment.errors.count, "error")
        | prohibited this comment from being saved:
      ul
        - @comment.errors.full_messages.each do |msg|
          li= msg
  .media
    = image_tag @user.avatar_url(:ico), :class => 'pull-left'
    .media-body
      = f.text_area :body, :rows => 2
      = f.hidden_field :user_id
      = f.hidden_field :article_id
      .actions
        = f.submit nil, :class => 'btn btn-primary' 

app/views/articles/comments/new.html.slim
.comments
  = render :partial => 'comment', :collection => @comments, :as => :comment
.comment-form
  = render 'form'