config/routes.rb
RssReader::Application.routes.draw do

  root :to => "channels#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks, :registrations => 'registrations'}
  ActiveAdmin.routes(self)

  resources :users, :only => :show
  
  resources :channels

  namespace :articles do
    resources :comments, :only => [:new, :create]
    post :star, :controller => :articles
    get :starred, :controller => :articles
    get :all, :controller => :articles
  end
  
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :channel_id, :description, :guid, :link, :pubDate, :title, :starred

  validates :title, :link, :description, :guid, :channel_id, :pubDate, :presence => true
  validates :guid, :uniqueness => true

  has_many :comments, :dependent => :destroy

  searchable do
    text :title, :boost => 2
    text :description
    integer :channel_id
  end

  def star_article
    self.toggle(:starred).save
  end
end

app/controllers/articles/articles_controller.rb
class Articles::ArticlesController < ApplicationController
  def all
    @user = current_user
    @articles = @user.articles
  end

  def star
    @user = current_user
    @article = Article.find(params[:article_id])
    
    if @article.star_article
      respond_to do |format|
        format.html{ render :partial => 'star', :locals => {:article => @article}, :layout => false}
      end
    end
  end

  def starred
    @user = current_user
    @articles = current_user.starred_articles
  end  
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < ApplicationController
  # GET /comments/new
  # GET /comments/new.json
  def new
    @user = current_user
    @article = Article.find(params[:article_id])
    @comments = @article.comments
    @comment = Comment.new(user_id: params[:user_id], article_id: params[:article_id])

    respond_to do |format|
      format.html{ render 'articles/comments/new',:layout => false}
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @user = current_user
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html{ render :partial => 'articles/comments/comment', :locals => {:comment => @comment},:layout => false }
      else
        format.html { render :text => 'There was an error when posting your comment, please try again later' }
      end
    end
  end
end

app/views/articles/articles/_article.html.slim
.article
  h4.title = link_to article.title, article.link, :target => '_blank'
  .star-container
    = render :partial => 'articles/articles/star', :locals => {:article => article}
  .description
    i.help-block = time_ago_in_words article.pubDate
    .text
      = article.description.sanitize.html_safe
  .comment-section
    h5 = t('navigation.titles.comment_section')
    = link_to t('actions.comment'), new_articles_comment_path(article_id: article.id), :class => 'ajax-comment btn', :remote => true

app/views/articles/articles/_star.html.slim
.star
  = link_to articles_star_path(:article_id => article.id), :id => 'star-link', :class => 'star-link', :method => :post, :remote => true do
    = article.starred? ? image_tag('star-gold24.png') : image_tag('star-white24.png')

app/views/articles/articles/all.html.slim
h2 = t('navigation.titles.all', :model => Article.model_name.human(:count => 2))

.articles-list
  = render :partial => 'articles/articles/article', :collection => @articles, :as => :article

app/views/articles/articles/starred.html.slim
h2 = t('navigation.titles.starred_articles')
.articles
  = render :partial => 'article', :collection => @articles, :as => :article